### PR TITLE
Feature ABFE

### PR DESCRIPTION
**Pull request by fjclark**
This PR makes ABFE calculations possible by allowing restraints to be passed to the Config.

### CODE REVIEW

**Comment by lohedges** [comment]
Thanks for this. I assume the restraints currently need to be configured via the Python API directly, i.e. the `restraints` option can't be used via the CLI interface, though an option is still automatically exposed for it.

For the `lambda_schedule` option I added some simple keywords to expose the common options to the CLI, but allow the user to pass an actual `LambaSchedule` object when using the Python API directly. Perhaps it's possible to do something similar for restraints too, e.g. restraint type, and indices. 

Ultimately we will need to come up with another configuration format to conveniently express the lambda schedule and restraints. This is probably too complicated for now, so I'd suggest simply not exposing the option to the CLI. This could be done in the `_create_parser` class method, e.g. by excluding the `restraints` parameter.

**Comment by fjclark** [comment]
Thanks, I've hidden this option from the CLI.

**Comment by chryswoods** [comment]
Just to add - see what I am doing in [feature_merge2](https://github.com/OpenBioSim/sire/tree/feature_merge2). This is adding in keywords for double decoupling and double annihilation lambda schedules. There's also code to create the ABFE merge molecule via `sire.morph.decouple` or `sire.morph.annihilate`. Maybe a route to expose in somd2 would be to have functions like these called via a keyword option, and have that keyword also trigger calculation and application of appropriate restraints?

**Comment by lohedges** [comment]
Brilliant, that sounds great. That's exactly how I've implemented the lambda schedule option at the moment. We'll still eventually need something flexible for power users, but this approach makes it very easy to expose the most common use cases.

**Comment by fjclark** [comment]
That looks great!

Just thinking about the coupling between `Config` and the system:

- Passing a constraint to the Config effectively couples it to the system as the constrain contains atoms from the system. Would it be best to try and minimise coupling between `Config` and the system by e.g. storing the restraint as a property of the perturbable molecule? This would be similar to how the restraints in GROMACS are part of the `.top` files. It would be nice to be able to pass a string representation of the restraint to the config, but then if the Config doesn't have access to the system, this couldn't be validated anyway.

- Alternatively, should a copy of the system be passed to the `Config`? I realise this goes against the point of having a separate `Config` class, this would allow e.g. restraint strings to be validated/ generated by `Config`. It might also simplify the validation discussed in https://github.com/OpenBioSim/somd2/pull/35 -  e.g. a sire dynamics class could be created at `lambda=0` and and sire errors would be raised only once, rather than once for every call to `_setup_dynamics`. This would avoid the duplication of logic in `https://github.com/OpenBioSim/sire/blob/devel/wrapper/Convert/__init__.py`.

**Pull request merged**
